GOOGLE_API_KEY         = "AIzaSyADogdagXESnJd1SMIPIbDu1xSI6ikxA7Y"
GOOGLE_CSE_ID          = "7662b93873bc24d56"
SCRAPINGBEE_KEY        = "A2WIMB93STNW51YSXPKQ6N1PLE1QQJO8F7M65UGUY60DAO73XJ8APRET755K2QA8Y8C8OFR56E8UTTTT"